parameter WORD_WIDTH = 16; 
parameter RAM_WORDS = 32768; // 2^A_WIDTH
parameter RAM_ADDRESS_WIDTH = $clog2(RAM_WORDS);
parameter ROM_WORDS = 32768; // 2^A_WIDTH
parameter ROM_ADDRESS_WIDTH = $clog2(ROM_WORDS);
parameter INSTRUCTION_WIDTH = WORD_WIDTH;

parameter VRAM_WORDS = 8192;
parameter VRAM_ADDRESS_WIDTH = $clog2(VRAM_WORDS);

// ADDRESS MAPPING
parameter [RAM_ADDRESS_WIDTH-1:0] HACK_ADDRESS_VRAM_START = 16384;
parameter [RAM_ADDRESS_WIDTH-1:0 ]HACK_ADDRESS_VRAM_END = 24575;
parameter [RAM_ADDRESS_WIDTH-1:0] HACK_ADDRESS_KEYBOARD = 'h6000;
parameter [RAM_ADDRESS_WIDTH-1:0] HACK_ADDRESS_GPIO_I = 'h6001;
parameter [RAM_ADDRESS_WIDTH-1:0] HACK_ADDRESS_GPIO_O = 'h6002;

parameter SRAM_ADDRESS_WIDTH = 24;

parameter HACK_GPIO_WIDTH = 8;
parameter HACK_GPIO_I_WIDTH = 4;
parameter HACK_GPIO_O_WIDTH = 4;

parameter HACK_SCREEN_WIDTH = 512;
parameter HACK_SCREEN_HEIGHT = 256;
parameter HACK_SCREEN_H_OFFSET = 64;//64;
parameter HACK_SCREEN_V_OFFSET = 112;

